Home page
KatrinDav/montecinema-app pull request #10
Opened 2022-03-17 14:17 UTC by KatrinDav

small changes in styles and structure of page;

2022-03-18 08:22 UTC, antanina-reznikava requested changes
Look's great, i added a few small suggestions :)

2022-03-18 08:22 UTC, antanina-reznikava commented on src/components/TopHeader.vue
>  </style>
Here the new line is needed at the end of the file.

2022-03-18 08:22 UTC, antanina-reznikava commented on src/pages/HomePage.vue
> +      >{{isVisible ? 'hide all' : 'see all'}}</p>
What do you think about moving this line to the `computed` property?

2022-03-18 08:22 UTC, antanina-reznikava commented on src/pages/HomePage.vue
>  </style>
Here also a new line is needed

2022-03-18 09:42 UTC, KatrinDav commented on src/components/TopHeader.vue
>  </style>
Yesterday I changed setting in VSC, so lines are added now.

2022-03-21 12:40 UTC, antanina-reznikava approved these changes

2022-03-26 11:08 UTC, merged