Movies genres
KatrinDav/montecinema-app pull request #9
Opened 2022-03-17 09:52 UTC by KatrinDav

functionality for getting unique movie genre in select oprions;

2022-03-17 15:13 UTC, szymonlicau requested changes
Nice work! 🙌 
I have a few suggestions for refactoring which I would really love for you to try out - they will help you in the long run and will let you use the full power of the vuex store you have introduced 😄

2022-03-17 15:13 UTC, szymonlicau commented on src/components/BaseButton.vue
>      <button :class="buttonClasses" @click="$emit('click')" :type="type">{{caption}}</button>
There is actually a much nicer - and more intuitive - way to set the contents of components like your `BaseButton` and that's the use of [slots](https://v2.vuejs.org/v2/guide/components-slots.html). Introducing a default slot here would allow us to instead of typing:

```html
<BaseButton caption="Hello I'm caption" />
```

we could type:

```html
<BaseButton>
  Hello I'm caption
</BaseButton>
```

This also allows to insert HTML content here such us icons and so on which a simple prop wouldn't be able to do!

It's quite easy to implement so I really encourage to try it out!

2022-03-17 15:13 UTC, szymonlicau commented on src/pages/HomePage.vue
> +        class="showItems"
I'd suggest to be consistent in how we name our classes and stick to it - you have `kebab-case` everywhelse else so `show-items` would be much more fitting 😄 
```suggestion
        class="show-items"
```

2022-03-17 15:13 UTC, szymonlicau commented on src/components/SelectInput.vue
> +    },
I have a proposition which you might like - we could move all of this into our store as `getters`.

We have access there to the movies already so we could also get the genres information out of them there and only access it wherever we need just like you accessed the `this.$store.getters.movies` 💡 

This would allow us to easily reference the same place from anywhere we need to because it's in our vuex store and we would keep our components much more slim! 😄

2022-03-18 09:57 UTC, KatrinDav commented on src/pages/HomePage.vue
> +        class="showItems"
Yes, you're right. Sometimes there is a chaos in names of these classes...

2022-03-18 10:33 UTC, KatrinDav commented on src/components/SelectInput.vue
> +    },
I moved that code to store. Hope it will be ok :)

2022-03-18 10:35 UTC, KatrinDav commented on src/components/BaseButton.vue
>      <button :class="buttonClasses" @click="$emit('click')" :type="type">{{caption}}</button>
I want to use some slots in next step of development. Thanks for hints!

2022-03-18 10:36 UTC, szymonlicau approved these changes

2022-03-19 12:17 UTC, merged